let fs = require("fs");
let path = require("path");
let paths = require("../config/paths.js");
let utils = require("./utils.js");

//Unicode parser
let parseUnicode = function (value) {
    return value.toString(16).toLowerCase();
};

//Append auto-generated header
let appendAutoGeneratedHeader = function (content) {
    content.push("//");
    content.push("// WARNING: THIS FILE IS AUTO-GENERATED. DO NOT EDIT IT.");
    content.push("// You can generate this file running the following command from the project root:");
    content.push("// $ make build");
    content.push("//");
    return content;
};

//Method to compile and build the icons SCSS file
let compileIconsSCSS = function () {
    //Compile icons
    let iconsList = utils.readJSON(paths.icons.list);
    let iconsContent = appendAutoGeneratedHeader([]); //Initialize icons content
    iconsContent.push("$icons: (");
    iconsList.forEach(function (item, index) {
        let sep = (index === iconsList.length - 1) ? "" : ","; //Separator
        iconsContent.push(`    "${item.id}": "${parseUnicode(item.unicode)}"${sep}`);
    });
    iconsContent.push(") !default;");
    return fs.writeFileSync(paths.icons.lib, iconsContent.join("\n"), "utf8"); //Write icons content
};

//Compile icons and colors
process.nextTick(function () {
    compileIconsSCSS(); //Compile icons SCSS
    //compileColorsSCSS(); //Compile colors SCSS
});


